### ISSUE TITLE
simple-system-monitor@ariel: curious default width in Cinnamon 5.8+

### ISSUE THREAD

**Issue by schorschii** [linuxmint/cinnamon-spices-desklets#1085] opened 2024-03-12 15:14 UTC
### Desklet version/Build date

1.2.0

### Cinnamon version

5.8+

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

NVIDIA with proprietary driver

### Desklet name and maintainer

simple-system-monitor@ariel @arielandrade

### What happened?

Your desklet contains a version switch which introduced a default width of 300px in Cinnamon >=5.8. This leads to a big empty space on the right side:
![image](https://github.com/linuxmint/cinnamon-spices-desklets/assets/17480795/fd310a8d-7ebb-4491-9f60-756118a319f0)

On previous Cinnamon versions, the width was not set manually but determined automatically, which is more meaningful in my opinion. Can we bring the auto width back to 5.8+ or was this change really intentional?

**Comment by rcalixte** [comment] 2024-03-13 01:19
The issue is that the width is fixed in pixels but the font size is set by scale so there isn't a way to match the two on every system dynamically. The intention would be for users to configure it when first adding it but we could do something like double the default scale too. The reason the width was added was to prevent the variable nature of the values from constantly resizing the desklet as well.

**Closed** 2024-05-07 10:33 UTC
Labels: bug

**Comment by schorschii** [comment] 2024-05-07 11:25
No problem, thanks for addressing this now. Unfortunately I have to say that there is no difference in the current version when using font scale value 1.0.

**Comment by rcalixte** [comment] 2024-05-08 01:57
> Unfortunately I have to say that there is no difference in the current version when using font scale value 1.0 (the big empty space on the right side is still there).

Ah, sorry for the confusion there. There is still the issue of the dynamic width being too distracting. Unless we restrict font choices to monospace fonts and give the desklet a fixed character length, this would be the only way I can think of for the static width to work. Would it be better to align the desklet in the center of the defined width as a workaround?
