### ISSUE TITLE
googleCalendar@javahelps.com - Error during loading

### ISSUE THREAD

**Issue by Pelt10** [linuxmint/cinnamon-spices-desklets#301] opened 2018-05-06 18:07 UTC
```
 * Build Date : 2018-05-06, 11:56 UTC
 * Cinnamon version : Cinnamon 3.6.7
 * Distribution : Debian Buster
 * No Graphic Card
 *  ~/.cinnamon/glass.log : https://gist.github.com/Pelt10/6d370a0fdbd23fe76b4e52159d087607
 * ~/.xsession-errors : https://gist.github.com/Pelt10/e6ba581718410a5b38a60a08698f5970
 ```

**Notify author of desklet**
@slgobinath

**Issue and Step to reproduce**
After I've download  and install the desklet, I try to add one on my desktop, and I'm getting this error : 
![image](https://user-images.githubusercontent.com/7582586/39676273-11995002-5168-11e8-8a24-61a4bbefd415.png)
"An error occurred during loading of  googleCalendar@javahelps.com. Check you used the last release before report this issue to the developer"

**Comment by slgobinath** [comment] 2018-05-06 18:54
Hi,
I am unable to track the exact problem using your log info.
Are you using any other desklets (to ensure the problem is with Google Calendar)?
Is this the first time you install this desklet (to see whether it happens after the recent update)?

**Comment by slgobinath** [comment] 2018-05-08 11:09
Have you installed `gcalcli` and configured it?

Executing the following command in the terminal should print your agenda:

```
gcalcli agenda "5/1/2018" "5/8/2018" --nostarted --tsv
```

**Comment by Pelt10** [comment] 2018-05-11 00:25
yes calcli is install and work fine : 

> gcalcli agenda "5/14/2018" "5/20/2018" --nostarted --tsv

Return my google agenda !

**Comment by slgobinath** [comment] 2018-12-13 14:15
Hi,
The desklet has been updated with some major changes now. Could you please try the latest one?
Please note that you need to install some additional dependencies now. We do not rely on gcalcli anymore.

**Comment by slgobinath** [comment] 2018-12-13 22:59
Thank you for updating me.

@jaszhix please close this issue.

Thanks

**Comment by jaszhix** [comment] 2018-12-13 23:03
@slgobinath Ok - just a heads up, you can add "Closes <PR #>" to your PRs, and they will close themselves when merged.

**Closed by jaszhix** 2018-12-13 23:03 UTC

**Comment by slgobinath** [comment] 2018-12-13 23:11
Sorry for troubling you.
I wasn't sure if some issues are actually fixed by my PR ^_^. I will use this feature for the issues which are sure to be fixed.
