### ISSUE TITLE
Analog clock not visible in Mint 17.3

### ISSUE THREAD

**Issue by ghardy2k** [linuxmint/cinnamon-spices-desklets#17] opened 2017-03-20 02:13 UTC
analog-clock@cobinja.de - Analog Clock

in mint 17.3, i can click it, move it, get to settings...but it is not visible on the desktop.

**Comment by Cos-mo** [comment] 2017-03-20 11:48
Works fine here on Mint 17,3.

Do you have the package gir1.2-rsvg-2.0 installed?

**Comment by Cobinja** [comment] 2017-03-21 06:58
Duplicate of #16, closed here

**Closed by Cobinja** 2017-03-21 06:58 UTC
