### ISSUE TITLE
quoteOfTheDay@tinnu: doesn't work

### ISSUE THREAD

**Issue by Ilis** [linuxmint/cinnamon-spices-desklets#118] opened 2017-05-09 18:42 UTC
@tinnu

Worked first time immediately after installation.

When file from /usr/share/games/fortunes/ was chosen (i. e. literature), desklet appears as small empty box. Click on it does nothing. There are no way to unchose file in settings.

**Comment by JessW** [comment] 2017-05-09 19:48
Hi there, could you let me know what version of Mint and Cinnamon you are using?  Also, does ~/.cinnamon/glass.log show errors related to this desklet?  Thanks!

**Comment by Ilis** [comment] 2017-05-10 17:26
Hi, @JessW 

ilis@deore ~ $ inxi -xxxSc0 -! 31
System:    Kernel: 4.4.0-72-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.2.7 (Gtk 3.18.9-1ubuntu3.3) dm: mdm Distro: Linux Mint 18.1 Serena

~/.cinnamon/glass.log
info t=2017-05-10T17:19:00.515Z Loaded desklet quoteOfTheDay@tinnu in 241 ms
info t=2017-05-10T17:19:00.519Z Cinnamon took 5010 ms to start
no errors

Also, fortunes-ru package installed, if it matter.

**Comment by JessW** [comment] 2017-05-10 21:09
Thanks for the info, @Ilis

I don't think I've tested it with Cinnamon 3.2, but I do think it might be a language issue.  Do you also have the English fortunes package installed, out of curiosity? I noticed just yesterday that there is a French version of this applet, which is what makes me think this one might not work correctly with other languages.  I will check it out when I get a chance, it might be a day or two though!

**Comment by JessW** [comment] 2017-05-11 00:59
@Ilis If you can, could you add a screen shot of the configuration window, or let me know the path of the file you have selected?  I was able to test the desklet with a randomly selected file from fortunes-ru:
/usr/share/games/fortunes/ru/drink
and it worked, but I am using Cinnamon 3.0.7.  I am not quite sure what you mean by "There are no way to unchose file in settings." in your first comment.  You should be able to type in the box that displays the path to the file, or use the file selector button next to the box with the path.  When I enter a the name of a file that doesn't exist, I do get the behavior you are describing.

I will try to get Cinnamon 3.2 on a spare box as well to see if I can reproduce what you're seeing.

**Comment by Ilis** [comment] 2017-05-11 04:53
@JessW ,
I used to chose different files, i. e.
/usr/share/games/fortunes/ru/computer
/usr/share/games/fortunes/literature

“no way to unchose” means that after fresh install no file is chosen, and if you chose one of files, you can't make this field empty, you just can choose one other file (and feature request is make possible multi files selection :) )

I'll make screen shot later, as soon as possible.

**Comment by Ilis** [comment] 2017-05-11 17:12
![2017-05-11_22-07-49](https://cloud.githubusercontent.com/assets/1223140/25962265/7aa14584-3696-11e7-921e-87a693e4134a.png)

Here are my screen shot. Small box to the left of settings window is a desklet :)

**Comment by JessW** [comment] 2017-05-11 18:45
@Ilis Thank you for the screenshot. It looks like a lot has changed in the recent Cinnamon releases. The good news is that I can reproduce the bug. I had an easier time getting Cinnamon 3.4, so I will work on it there, and hopefully that will fix the problem for you as well. Will let you know when I have something you can try, if you'd like.

Thanks so much for letting me know it's so broken!

**Comment by Ilis** [comment] 2017-05-11 19:21
@JessW , thank you and hope you will keep me informed. When desklet will work, I make localization for it.

**Comment by JessW** [comment] 2017-05-12 17:44
That would be fantastic, @Ilis !
Will keep you posted.

**Comment by JessW** [comment] 2017-05-17 14:20
Hi @Ilis, I think I've fixed the problem, at least the desklet works correctly in Cinnamon 3.4 now.  Since I haven't tested in with Cinnamon 3.2, would you be willing to test it out before I submit the pull request?  My changes are here:
https://github.com/JessW/cinnamon-spices-desklets

If you put the contents of 
cinnamon-spices-desklets/quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/
in

**Comment by Ilis** [comment] 2017-05-17 18:29
@JessW , well, I put files from 3.2 folder of your repository to my local folder, desklet crashed with log message "metadata.js not found". I added that file from upper folder of repository and desklet started do the job.

When I change quotes file in settings, new quotes are shown.

Unfortunately, background is not transparent:

![2017-05-17_23-22-24](https://cloud.githubusercontent.com/assets/1223140/26169835/8035c0c6-3b58-11e7-9328-ee6029486600.png)

**Comment by Ilis** [comment] 2017-05-17 19:05
I'm very sorry, background is not transparent when settings window is opened. Elsewhere it is transparent.

So, only metadata.js needed...

**Comment by JessW** [comment] 2017-05-18 13:35
That's great!  I was puzzled why it wouldn't be transparent.  I don't see that in Cinnamon 3.4, but I guess it's kind of a nice feature to show what is being configured.

My understanding is that when the desklet is installed in the regular way, everything in 
cinnamon-spices-desklets/quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/
will be included, even if you are running Cinnamon 3.2+  If you check out
http://developer.linuxmint.com/reference/git/cinnamon-tutorials/xlet-versioning.html
it recommends putting metadata.json in that top level directory.  But you are right, the desklet won't work without it!

I appreciate your help, @Ilis!

**Comment by Ilis** [comment] 2017-05-20 16:50
It doesn't work after last update. Glass log has no errors.

**Comment by JessW** [comment] 2017-05-20 21:59
Hm, does ~/.xsession-errors have any related errors, and do you happen to
know what was updated? Is there just no quote displayed? I'm ​bummed to
hear it's stopped working.

It might be a few days, but I will see if I have updates on my Cinnamon 3.4
system to see if it stops working there, too. Thank you for letting me know!

**Comment by Ilis** [comment] 2017-05-21 09:38
Hi, @JessW !
It was work when installed from 3.2 folder of your repository. Now I updated it from Spices repository (using standard update button of Preferences → Applets). I think it will work for me if I update it from your repository again, but it will not work for other 3.2 Cinnamon users.

**Comment by JessW** [comment] 2017-05-22 14:00
@Ilis I see, I see.  That is totally my fault.  I have one more test I want to run before I make the pull request to the main Spices repo, and I just haven't gotten to it yet.  Soon, I hope!

Thank you also for your translation, I really appreciate it!

**Comment by Ilis** [comment] 2017-05-27 19:01
Finally it works!

Thank you, @JessW !

**Comment by JessW** [comment] 2017-05-27 19:16
I'm glad to hear it!  Thank you for bringing it to my attention, @Ilis :)  Can you close the issue too, when you get a chance?

**Comment by JosephMcc** [comment] 2017-05-27 19:24
Done :)

**Closed by JosephMcc** 2017-05-27 19:24 UTC

**Comment by JessW** [comment] 2017-05-27 19:26
Thank you!
