### ISSUE TITLE
yfquotes@thegli: Cinnamon not able to boot with extension enabled and Wi-Fi OFF

### ISSUE THREAD

**Issue by teto90** [linuxmint/cinnamon-spices-desklets#760] opened 2022-03-20 10:35 UTC
* **Desklet version/Build date (0.8.0)**
 * **Cinnamon version (Cinnamon 5.2.7)**
 * **Distribution - (Linux mint 20.3 una)**
 * **Linuxmint 20.3 una**
 *  **DEV-1 Mesa Intel(R) HD Graphics 520 (SKL GT2)**
 *  **DEV-2: AMD Sun XT**
 *  **Display:** x11 server: X.Org 1.20.13 driver: ati,modesetting,radeon unloaded: fbdev,vesa 
    resolution: 1366x768~60Hz, 1920x1080~60Hz 
    OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 21.2.6 
    direct render: Yes 
 * **xsession-errors** 

_(I THINK) WI-FI OFF_
(blueberry-tray.py:1859): Bluetooth-WARNING **: 11:03:35.786: Error setting property 'Powered' on interface org.bluez.Adapter1:GDBus.Error:org.bluez.Error.Blocked: Blocked through rfkill (g-io-error-quark, 36)

(xapp-sn-watcher:1698): GLib-GObject-CRITICAL **: 11:04:00.700: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(xapp-sn-watcher:1698): GLib-GIO-CRITICAL **: 11:04:00.700: g_dbus_interface_skeleton_flush: assertion 'G_IS_DBUS_INTERFACE_SKELETON (interface_)' failed

(xapp-sn-watcher:1698): GLib-GObject-CRITICAL **: 11:04:00.700: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(xapp-sn-watcher:1698): GLib-GIO-CRITICAL **: 11:04:00.700: g_dbus_interface_skeleton_flush: assertion 'G_IS_DBUS_INTERFACE_SKELETON (interface_)' failed

(xapp-sn-watcher:1698): GLib-GObject-WARNING **: 11:04:00.700: invalid (NULL) pointer instance

(xapp-sn-watcher:1698): GLib-GObject-CRITICAL **: 11:04:00.700: g_signal_emit_by_name: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
cinnamon-session[1369]: WARNING: t+32,58405s: Detected that screensaver has left the bus

_(I THINK) WHEN I PLUG WI-FI (WI-FI ON)_
Cjs-Message: 11:04:22.061: JS LOG: [LookingGlass/info] Loaded desklet yfquotes@thegli in 50158 ms
Cjs-Message: 11:04:22.073: JS LOG: [LookingGlass/info] Loaded applet workspace-switcher@cinnamon.org in 12 ms
Cjs-Message: 11:04:22.087: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 14 ms
Cjs-Message: 11:04:22.088: JS LOG: [LookingGlass/info] NaNms
Cjs-Message: 11:04:22.106: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 19 ms
Cjs-Message: 11:04:22.139: JS LOG: [LookingGlass/info] Role locked: panellauncher
Cjs-Message: 11:04:22.145: JS LOG: [LookingGlass/info] Loaded applet panel-launchers@cinnamon.org in 39 ms

** (csd-power:1527): CRITICAL **: 11:04:22.169: abs_to_percentage: assertion 'max > min' failed
Cjs-Message: 11:04:22.212: JS LOG: [LookingGlass/info] Loaded applet window-list@cinnamon.org in 67 ms
Cjs-Message: 11:04:22.243: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 31 ms
Cjs-Message: 11:04:22.255: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: nm-applet (:1.52/org/x/StatusIcon/Icon)
Cjs-Message: 11:04:22.265: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: blueberry (:1.67/org/x/StatusIcon/Icon)
Cjs-Message: 11:04:22.270: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintreport (:1.73/org/x/StatusIcon/Icon)
Cjs-Message: 11:04:22.274: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintUpdate.py (:1.70/org/x/StatusIcon/Icon)
Cjs-Message: 11:04:22.313: JS LOG: [LookingGlass/info] Hiding XAppStatusIcon (we have an applet): nm-applet (:1.52/org/x/StatusIcon/Icon)
Cjs-Message: 11:04:22.326: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 83 ms
Cjs-Message: 11:04:22.501: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 175 ms
Cjs-Message: 11:04:22.502: JS LOG: [LookingGlass/info] AppletManager started in 50989 ms
Cjs-Message: 11:04:22.505: JS LOG: [LookingGlass/info] Cinnamon took 51576 ms to start

 ```

@thegli  

**Notify author of desklet**
@thegli 

**Issue**
Cinnamon don't boot up if yahoo finance quotes is enabled but PC has not access to internet. I'm using WI-FI on my machine.
Not able to access also trying to launch the session from tty with "startx".
When PC is able to connect to WI-FI everything seems to boot normally and autonomously.

If I start the PC with WI-FI ON everything goes fine.

If I start the PC with WI-FI OFF and after encountering the problem I switch on the WI-FI, I'm able to enter my cinnamon session, but seems to have strange behaviour. Shortcut not working, Nemo very slow and other minor stuff.


**Steps to reproduce**
no internet acces
desklet enabled
start the PC


**Expected behaviour**
boot normally on cinnamon with desklet enabled but without WI-FI


**Other information**
Error when I boot without WI-FI

Error:Gio.ResolverError: Error resolving "query1.finance.yahoo.com": No address associated with hostname


Thanks a lot for the effort ;)

**Comment by thegli** [comment] 2022-05-16 22:41
@teto90 First of all, sorry for the late response, and second, thank you for the detailed documentation of the issue.

I can reproduce the behavior, and I'm about to release a fix version 0.8.1 that changes the way how the data are fetched (#766).
If all works out, the new desklet version should be available within the next few days.
Please let me know if this one solves the issue for you.

**Comment by teto90** [comment] 2022-05-17 05:16
Thanks a lot Thomas.
It's the first time that I signal a bug on github and you are making it a great experience for me.
I definitely send you a feedback as soon as possible.
Stefano
--
Inviato da Libero Mail per Android martedì, 17 maggio 2022, 00:41AM +02:00 da Thomas Egli  ***@***.*** :

***@***.*** First of all, sorry for the late response, and second, thank you for the detailed documentation of the issue.

**Comment by teto90** [comment] 2022-07-11 18:28
Any news about the new release?

Stefano

**Comment by thegli** [comment] 2022-08-20 17:01
The PR was merged today :smiley: Let me know if the problem you reported is fixed with the new version.

**Comment by thegli** [comment] 2022-09-23 17:03
@teto90 Any chance to re-test?

**Comment by teto90** [comment] 2022-09-25 17:29
Ciao,

What do I need to test? A new version?

Explain me and I'll sure try to help you

Stefano

23 set 2022 19:03:24 Thomas Egli ***@***.***>:

**Comment by thegli** [comment] 2022-09-25 18:57
Yes please, the current version (0.8.2) distributed via Update Manager.

**Comment by thegli** [comment] 2023-07-07 16:17
@teto90 If the problem is solved for you, can you close this issue?

**Comment by teto90** [comment] 2023-07-07 18:31
For me absolutely closed!

Thanks a lot

----------------------------------------

2023-07-07T16:17:28Z Thomas Egli ***@***.***>:

**Comment by fredcw** [comment] 2023-07-07 20:14
@teto90 There should be a close button at the bottom of the page.

**Comment by thegli** [comment] 2023-07-11 18:52
@teto90 Thanks for your willingness to close the issue. Since you opened the issue in the first place, only you can close it. As @fredcw pointed out, there is a Close button when you browse to this page. Whenever you're ready :smiley:

**Comment by teto90** [comment] 2023-07-13 11:14
Oh, ok! It was my first issue ever.
I'll close as soon as possible!

:)

----------------------------------------

2023-07-11T18:52:49Z Thomas Egli ***@***.***>:

**Closed** 2023-07-13 11:29 UTC
